let data=[
        {
            id:1,
            image:"/Assets/pic4.jpg",
            name:"Monica",
            age:"24"
        },
        {
            id:2,
            image:"/Assets/pic1.jpg",
            name:"Rachel",
            age:"26"
        },
        {
            id:3,
            image:"/Assets/pic3.jpg",
            name:"Chandler",
            age:"27"
        },
        {
            id:4,
            image:"/Assets/pic6.jpg",
            name:"Joey",
            age:"27"
        },
        {
            id:5,
            image:"/Assets/pic5.jpg",
            name:"Ross",
            age:"29"
        },
        {
            id:6,
            image:"/Assets/pic2.jpg",
            name:"Phoebe",
            age:"25"
        }
    ]
    export default data
